"""Transaction / purchase-event schemas."""
from datetime import datetime, timezone
from enum import Enum
from typing import Literal, Optional

from pydantic import BaseModel, Field


class MerchantCategory(str, Enum):
    """Merchant Category Codes mapped to human-readable names.

    The rules-filter uses these to quickly decide whether a transaction
    is worth checking further (e.g. electronics qualify for purchase
    protection; airlines qualify for travel-delay).
    """
    ELECTRONICS = "electronics"
    CLOTHING = "clothing"
    SPORTING_GOODS = "sporting_goods"
    JEWELRY = "jewelry"
    HOME_APPLIANCES = "home_appliances"
    AIRLINE = "airline"
    HOTEL = "hotel"
    RESTAURANT = "restaurant"          # typically excluded
    GROCERY = "grocery"                # typically excluded
    GAS_STATION = "gas_station"        # typically excluded
    CASH_ADVANCE = "cash_advance"      # always excluded
    OTHER = "other"


class TransactionStatus(str, Enum):
    PENDING = "pending"        # just ingested, not yet processed
    PROCESSED = "processed"    # ran through detection pipeline
    SKIPPED = "skipped"        # failed rules filter — no further action


class TransactionBase(BaseModel):
    card_id: str
    card_member_id: str
    merchant_name: str
    merchant_category: MerchantCategory
    amount_usd: float = Field(gt=0)
    currency: str = "USD"
    # For travel-delay: link to a flight/booking reference
    travel_booking_ref: Optional[str] = None
    # For return protection: signal that store refused return
    store_refused_return: bool = False
    # For travel-delay: actual delay in minutes (simulated)
    flight_delay_minutes: Optional[int] = None
    purchased_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc).replace(tzinfo=None))


class TransactionSimulateRequest(BaseModel):
    """Input for POST /transactions/simulate.

    All fields optional — omitted ones are randomly generated by the
    ingestion service so judges can click "simulate" with no input.
    """
    card_id: Optional[str] = None
    merchant_name: Optional[str] = None
    merchant_category: Optional[MerchantCategory] = None
    amount_usd: Optional[float] = Field(default=None, gt=0)
    travel_booking_ref: Optional[str] = None
    store_refused_return: Optional[bool] = None
    flight_delay_minutes: Optional[int] = None
    purchased_at: Optional[datetime] = None


class Transaction(TransactionBase):
    id: str
    status: TransactionStatus = TransactionStatus.PENDING
    skip_reason: Optional[str] = None
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc).replace(tzinfo=None))


class TransactionResponse(Transaction):
    """Returned after simulate — includes detection result."""
    detection_result: Optional[dict] = None
